### ISSUE TITLE
Suggestion: Human-readable date format

### ISSUE THREAD

**Issue by DenverCoder1** [icanhazstring/random-issue-picker#14]
Currently the creation date is displayed using ISO 8601 (example: `2020-03-19T04:23:27Z`) which does not have spaces so can be difficult to read.

My suggestion would be to format this in a more human-readable way such as `Mar 19, 2020, 4:23 AM UTC`.
If possible, it could convert it to the current user's timezone as well (ex. `Mar 18, 2020, 9:23 PM GMT-7`).

I am willing to attempt implementing this.

**Comment by icanhazstring** [comment]
If you want. You can collaborate with #11. There is already the ability to "parse" incoming `created_date` with a `DateTime` object. So you could use `->format(...)` while adding it to the output.

**Comment by icanhazstring** [comment]
Solved with #11
