### ISSUE TITLE
Github PR template refers to non-existing CONTRIBUTING.md

### ISSUE THREAD

**Issue by martijnengler** [icanhazstring/random-issue-picker#17]
In the file [`.github/PULL_REQUEST_TEMPLATE.md`](https://github.com/icanhazstring/random-issue-picker/blob/master/.github/PULL_REQUEST_TEMPLATE.md) there's a reference to `CONTRIBUTING.md`, but the document doesn't actually _exist_.

It should probably either be created, or removed from the template. 

I think _creating_ the document would be the best solution, but I'm probably not the most qualified person to actually do that. Maybe [a document like this](https://gist.github.com/PurpleBooth/b24679402957c63ec426) could be a good starting point?

**Comment by icanhazstring** [comment]
You could also simply point to the "how to contribute" of the readme. Or simply extract this part into a `CONTRIBUTE.md`. Either way is fine with me.

The file you linked is way to overboard with this small library and is more of a push back to ppl who just want to contribute quickly.

**Comment by martijnengler** [comment]
Extracting is probably overcomplicating things for a small repo; agree with your sentiment about that. :)

Provided a link to the correct part of the README, should be enough.

It was just that I got genuinely confused with my other PR, because I couldn't find the document.
