### ISSUE TITLE
[BUG] .docker folder is missing

### ISSUE THREAD

**Issue by tomasnorre** [icanhazstring/random-issue-picker#2]
**Describe the bug**
Currently the docker-compose.yml is not of any use as the referenced .docker folder is missing

**Comment by icanhazstring** [comment]
Added a new .docker/Dockerfile
You can use `make up` to build and run the container

**Comment by tomasnorre** [comment]
Did you forget to push it ? I don't see it in the master branch

**Comment by icanhazstring** [comment]
You were right. Had it ignored. Now its there 👍

**Comment by tomasnorre** [comment]
No... :(

**Comment by tomasnorre** [comment]
Last commit is still from me, 8 hours ago.

**Comment by icanhazstring** [comment]
My push was interrupted :D
But now its finally there ;)
