### ISSUE TITLE
Publishing this Docker image to the DockerHub automatically

### ISSUE THREAD

**Issue by peter279k** [icanhazstring/random-issue-picker#26]
As title, I think we can consider letting the Docker image building test be automated during the every GitHub action workflows.

We can also let above Docker image be automated to publish to the DockerHub once every building is completed.

Please refer these [YAML files](https://github.com/peter279k/docker_couchdb_ext/tree/master/.github/workflows) to know more details about above description.

**Comment by icanhazstring** [comment]
Currently I don't plan to add a docker image as it needs to be maintained as well. You can however create a repo yourself which can build a docker image for this repo which I'll be happy to link in the readme.

**Comment by peter279k** [comment]
Thanks for your reply. I think it's a good idea to let me create another repository to do that.

I will close this issue now. I will create the PR to provide the link on README once above my repository is done :).
