### ISSUE TITLE
[QUESTION] Why are you restricting it to PHP 7.3 

### ISSUE THREAD

**Issue by tomasnorre** [icanhazstring/random-issue-picker#6]
Why are you restricting this to PHP 7.3, it's working with PHP 7.2 as well.

I know that PHP 7.3 is the best case scenario, and you can force people a little to update, but I personally still have to battle with some PHP 7.0 projects, so having to jump back and fort for this tool, is just one more obstacle not to use it.

And I really enjoy it, helps me learn from random PHP Issues.

**Comment by icanhazstring** [comment]
That is pretty simple to answer.
Every new project I start has the minimum requirement of the current full supported version.

As for the current day of writing: This is php7.3
https://www.php.net/supported-versions.php

For the most part, I am running my tools using docker. So I don't have the problem of conflicting PHP versions.

**Comment by tomasnorre** [comment]
Perhaps we should update the readme to run it with the docker variant instead, this would probably also help the problem here: 
https://dev.to/kaeptnkrunch/comment/15efi

If you can update the readme I will update the article accordingly.

**Comment by icanhazstring** [comment]
Hm, that is a strange problem 🤔

**Comment by tomasnorre** [comment]
This was more a Question than an issue. Closing
