### ISSUE TITLE
[Feature] Add date related information to output

### ISSUE THREAD

**Issue by icanhazstring** [icanhazstring/random-issue-picker#8]
**Is your feature request related to a problem? Please describe.**
I would like to have more information about the picked issue.
For example the creation date of the issue itself. Or other date-related information that might help you pick the issue.

**Describe the solution you'd like**
Improve the `IssueModel` to be able to read the needed values.

**Comment by insaurabh** [comment]
@icanhazstring 

What I understood is we have to show more details about the picked issue like `date`. 

If I understood correctly can I work on this?

**Comment by icanhazstring** [comment]
@insaurabh sure go ahead.
I would like to show the created date of the issue for example (besides the URL, title and body)
If you find any other information that could be helpful, go ahead :)

**Comment by icanhazstring** [comment]
@insaurabh same goes for you. If you need any help, don't hesitate to ask 👍

**Comment by icanhazstring** [comment]
Solved with #12
