### ISSUE TITLE
[Feature] Improve console output

### ISSUE THREAD

**Issue by icanhazstring** [icanhazstring/random-issue-picker#9]
The current console output of an issue is pretty simple. The output could be a bit more improved.
For example, using some colors or even a table approach.

If you pick this issue you have almost free reign of what you want to do.
The only limitation is your imagination. And my approval ;)

**Comment by DenverCoder1** [comment]
I would love to help with this!

**Comment by icanhazstring** [comment]
Hi @DenverCoder1 I would appreciate it! Go ahead. Thank you 👍 
If you need any help, don't hesitate to ask.

**Comment by icanhazstring** [comment]
Merged 👍 
Thanks again.
